version: "3.9"
services:

  resource-db:
    image: postgres:16
    container_name: resource-db
    environment:
      POSTGRES_DB: resource_db
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: 1
    ports:
      - "5431:5432"
    networks:
      - app-network


  song-db:
    image: postgres:16
    container_name: song-db
    environment:
      POSTGRES_DB: song_db
      POSTGRES_USER: song_user
      POSTGRES_PASSWORD: song_password
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge